import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedesqueciasenhawidget/generated/GeneratedButtonWidget9.dart';
import 'package:flutterapp/vtrapp/generatedesqueciasenhawidget/generated/GeneratedNosepreocupeInformeseuemaildecadastroeiremosenviarumlin.dart';
import 'package:flutterapp/vtrapp/generatedesqueciasenhawidget/generated/GeneratedHeaderWidget5.dart';
import 'package:flutterapp/vtrapp/generatedesqueciasenhawidget/generated/GeneratedInputWidget14.dart';

/* Frame Esqueci a Senha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEsqueciaSenhaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedHeaderWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 122.0,
                child:
                    GeneratedNosepreocupeInformeseuemaildecadastroeiremosenviarumlin(),
              ),
              Positioned(
                left: 16.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget14(),
              ),
              Positioned(
                left: 16.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 36.0,
                child: GeneratedButtonWidget9(),
              )
            ]),
      ),
    ));
  }
}
