import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedvisualizandoprodutowidget/generated/GeneratedBottomMenuWidget13.dart';
import 'package:flutterapp/vtrapp/generatedvisualizandoprodutowidget/generated/GeneratedIconsWidget100.dart';
import 'package:flutterapp/vtrapp/generatedvisualizandoprodutowidget/generated/GeneratedImage1Widget.dart';
import 'package:flutterapp/vtrapp/generatedvisualizandoprodutowidget/generated/GeneratedHeaderWidget17.dart';
import 'package:flutterapp/vtrapp/generatedvisualizandoprodutowidget/generated/GeneratedGarantiavitalciaWidget.dart';

/* Frame Visualizando produto
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVisualizandoprodutoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 641.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 641.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 56.0,
                              child: GeneratedBottomMenuWidget13(),
                            ),
                            Positioned(
                              left: 125.0,
                              top: 387.0,
                              right: null,
                              bottom: null,
                              width: 117.0,
                              height: 32.0,
                              child: GeneratedGarantiavitalciaWidget(),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 93.0,
                              right: null,
                              bottom: null,
                              width: 306.0,
                              height: 274.0,
                              child: GeneratedImage1Widget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 16.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedIconsWidget100(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 56.0,
                              child: GeneratedHeaderWidget17(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
