import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedseguranawidget1/generated/GeneratedVectorWidget128.dart';
import 'package:flutterapp/vtrapp/generatedseguranawidget1/generated/GeneratedInputWidget23.dart';
import 'package:flutterapp/vtrapp/generatedseguranawidget1/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/vtrapp/generatedseguranawidget1/generated/GeneratedInputWidget19.dart';
import 'package:flutterapp/vtrapp/generatedseguranawidget1/generated/GeneratedInputWidget21.dart';
import 'package:flutterapp/vtrapp/generatedseguranawidget1/generated/GeneratedBottomMenuWidget8.dart';
import 'package:flutterapp/vtrapp/generatedseguranawidget1/generated/GeneratedHeaderWidget10.dart';

/* Frame Segurança
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSeguranaWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 352.0,
        height: 636.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedHeaderWidget10(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedVectorWidget128(),
              ),
              Positioned(
                left: 16.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget19(),
              ),
              Positioned(
                left: 16.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget21(),
              ),
              Positioned(
                left: 16.0,
                top: 277.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget23(),
              ),
              Positioned(
                left: 15.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedBottomMenuWidget8(),
              )
            ]),
      ),
    ));
  }
}
