import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedloginclientewidget/generated/GeneratedButtonWidget7.dart';
import 'package:flutterapp/vtrapp/generatedloginclientewidget/generated/GeneratedInputWidget5.dart';
import 'package:flutterapp/vtrapp/generatedloginclientewidget/generated/GeneratedLogAmarelo_32Widget.dart';
import 'package:flutterapp/vtrapp/generatedloginclientewidget/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/vtrapp/generatedloginclientewidget/generated/GeneratedButtonWidget6.dart';
import 'package:flutterapp/vtrapp/generatedloginclientewidget/generated/GeneratedHeaderWidget3.dart';
import 'package:flutterapp/vtrapp/generatedloginclientewidget/generated/GeneratedInputWidget6.dart';

/* Frame Login Cliente
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginClienteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 16.0,
                top: 280.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget5(),
              ),
              Positioned(
                left: 16.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget6(),
              ),
              Positioned(
                left: 15.0,
                top: 491.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget5(),
              ),
              Positioned(
                left: 15.0,
                top: 537.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget6(),
              ),
              Positioned(
                left: 15.0,
                top: 583.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget7(),
              ),
              Positioned(
                left: 86.0,
                top: 70.0,
                right: null,
                bottom: null,
                width: 180.0,
                height: 180.0,
                child: GeneratedLogAmarelo_32Widget(),
              ),
              Positioned(
                left: -1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedHeaderWidget3(),
              )
            ]),
      ),
    ));
  }
}
