import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedlogowidget/generated/GeneratedLogAmarelo_31Widget1.dart';
import 'package:flutterapp/vtrapp/generatedlogowidget/generated/Generated313401819_49083324973241Widget.dart';

/* Frame Logo
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLogoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 352.0,
        height: 195.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 160.0,
                child: GeneratedLogAmarelo_31Widget1(),
              ),
              Positioned(
                left: 176.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 160.0,
                child: Generated313401819_49083324973241Widget(),
              )
            ]),
      ),
    ));
  }
}
