import 'package:flutter/material.dart';

/* Frame TelaTeste
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTelaTesteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 291.0,
        height: 393.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            color: Color.fromARGB(255, 76, 194, 181),
          ),
        ),
      ),
    ));
  }
}
