import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedInputWidget.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedInputWidget2.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedInputWidget3.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedHeaderWidget.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedInputWidget1.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedBottomMenuWidget.dart';
import 'package:flutterapp/vtrapp/generatedmeusdadoswidget/generated/GeneratedInputWidget4.dart';

/* Frame Meus dados
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMeusdadosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 706.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 636.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 73.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 82.0,
                              child: GeneratedInputWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 168.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 85.0,
                              child: GeneratedInputWidget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 323.0,
                              height: 80.0,
                              child: GeneratedInputWidget2(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 366.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 76.0,
                              child: GeneratedInputWidget3(),
                            ),
                            Positioned(
                              left: 10.0,
                              top: 666.0,
                              right: null,
                              bottom: null,
                              width: 341.0,
                              height: 40.0,
                              child: GeneratedButtonWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 580.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 56.0,
                              child: GeneratedBottomMenuWidget(),
                            ),
                            Positioned(
                              left: -2.0,
                              top: -5.0,
                              right: null,
                              bottom: null,
                              width: 362.0,
                              height: 60.0,
                              child: GeneratedHeaderWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 467.0,
                              right: null,
                              bottom: null,
                              width: 328.0,
                              height: 82.0,
                              child: GeneratedInputWidget4(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
