import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedperfilwidget/generated/GeneratedListadeItensWidget.dart';
import 'package:flutterapp/vtrapp/generatedperfilwidget/generated/GeneratedHeaderWidget1.dart';
import 'package:flutterapp/vtrapp/generatedperfilwidget/generated/GeneratedBottomMenuWidget2.dart';

/* Frame Perfil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPerfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedHeaderWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 72.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 216.0,
                child: GeneratedListadeItensWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 584.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedBottomMenuWidget2(),
              )
            ]),
      ),
    ));
  }
}
