import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedsobrenswidget/generated/GeneratedSobrens307446632_1531421Widget.dart';
import 'package:flutterapp/vtrapp/generatedsobrenswidget/generated/GeneratedHeaderWidget19.dart';
import 'package:flutterapp/vtrapp/generatedsobrenswidget/generated/GeneratedInputWidget28.dart';
import 'package:flutterapp/vtrapp/generatedsobrenswidget/generated/GeneratedButtonWidget16.dart';
import 'package:flutterapp/vtrapp/generatedsobrenswidget/generated/GeneratedAssistivetextWidget46.dart';

/* Frame Sobre nós
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSobrensWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 360.0,
      height: 640.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          clipBehavior: Clip.none,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.zero,
              child: Container(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 15.0,
              top: 587.0,
              right: null,
              bottom: null,
              width: 329.0,
              height: 36.0,
              child: GeneratedButtonWidget16(),
            ),
            Positioned(
              left: 4.0,
              top: 420.0,
              right: null,
              bottom: null,
              width: 328.0,
              height: 26.0,
              child: GeneratedInputWidget28(),
            ),
            Positioned(
              left: 20.0,
              top: 462.0,
              right: null,
              bottom: null,
              width: 326.0,
              height: 105.0,
              child: GeneratedAssistivetextWidget46(),
            ),
            Positioned(
              left: 0.0,
              top: 56.0,
              right: null,
              bottom: null,
              width: 360.0,
              height: 334.0,
              child: GeneratedSobrens307446632_1531421Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 362.0,
              height: 56.0,
              child: GeneratedHeaderWidget19(),
            )
          ]),
    ));
  }
}
