import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedmainloginwidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/vtrapp/generatedmainloginwidget/generated/GeneratedLogAmarelo_31Widget.dart';
import 'package:flutterapp/vtrapp/generatedmainloginwidget/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/vtrapp/generatedmainloginwidget/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/vtrapp/generatedmainloginwidget/generated/GeneratedVTRAppWidget.dart';
import 'package:flutterapp/vtrapp/generatedmainloginwidget/generated/GeneratedButtonWidget2.dart';

/* Frame Main Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromRGBO(18, 19, 18, 1),
                ),
              ),
              Positioned(
                left: 86.0,
                top: 298.0,
                right: null,
                bottom: null,
                width: 190.0,
                height: 37.0,
                child: GeneratedVTRAppWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 459.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget2(),
              ),
              Positioned(
                left: 15.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget3(),
              ),
              Positioned(
                left: 15.0,
                top: 588.0,
                right: null,
                bottom: null,
                width: 329.0,
                height: 36.0,
                child: GeneratedButtonWidget4(),
              ),
              Positioned(
                left: 79.0,
                top: 51.0,
                right: null,
                bottom: null,
                width: 200.0,
                height: 200.0,
                child: GeneratedLogAmarelo_31Widget(),
              )
            ]),
      ),
    ));
  }
}
