import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedsearchwidget/generated/GeneratedPesquisaWidget1.dart';

/* Frame Search
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 382.0,
        height: 218.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 21.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 44.0,
                child: GeneratedPesquisaWidget1(),
              )
            ]),
      ),
    ));
  }
}
