import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatedredefinirsenhawidget/generated/GeneratedButtonWidget10.dart';
import 'package:flutterapp/vtrapp/generatedredefinirsenhawidget/generated/GeneratedInputWidget15.dart';
import 'package:flutterapp/vtrapp/generatedredefinirsenhawidget/generated/GeneratedInputWidget17.dart';
import 'package:flutterapp/vtrapp/generatedredefinirsenhawidget/generated/GeneratedHeaderWidget6.dart';
import 'package:flutterapp/vtrapp/generatedredefinirsenhawidget/generated/GeneratedProntoagorasvocinserirumanovasenhaabaixolembrandoqueDev.dart';

/* Frame Redefinir Senha
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRedefinirSenhaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedHeaderWidget6(),
              ),
              Positioned(
                left: 16.0,
                top: 86.0,
                right: null,
                bottom: null,
                width: 330.0,
                height: 152.0,
                child:
                    GeneratedProntoagorasvocinserirumanovasenhaabaixolembrandoqueDev(),
              ),
              Positioned(
                left: 16.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget15(),
              ),
              Positioned(
                left: 16.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 82.0,
                child: GeneratedInputWidget17(),
              ),
              Positioned(
                left: 16.0,
                top: 490.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 36.0,
                child: GeneratedButtonWidget10(),
              )
            ]),
      ),
    ));
  }
}
