import 'package:flutter/material.dart';
import 'package:flutterapp/vtrapp/generatednewswidget/generated/GeneratedSchedulebroWidget.dart';
import 'package:flutterapp/vtrapp/generatednewswidget/generated/GeneratedBottomMenuWidget10.dart';
import 'package:flutterapp/vtrapp/generatednewswidget/generated/GeneratedVectorWidget149.dart';
import 'package:flutterapp/vtrapp/generatednewswidget/generated/GeneratedSemnovidadesatomoementoPostaremosnovosprodutosenovidade.dart';
import 'package:flutterapp/vtrapp/generatednewswidget/generated/GeneratedHeaderWidget11.dart';

/* Frame News
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNewsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 352.0,
        height: 636.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            clipBehavior: Clip.none,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedHeaderWidget11(),
              ),
              Positioned(
                left: 20.0,
                top: 20.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedVectorWidget149(),
              ),
              Positioned(
                left: 11.0,
                top: 110.0,
                right: null,
                bottom: null,
                width: 339.0,
                height: 62.0,
                child:
                    GeneratedSemnovidadesatomoementoPostaremosnovosprodutosenovidade(),
              ),
              Positioned(
                left: 42.0,
                top: 171.0,
                right: null,
                bottom: null,
                width: 267.0,
                height: 293.0,
                child: GeneratedSchedulebroWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 56.0,
                child: GeneratedBottomMenuWidget10(),
              )
            ]),
      ),
    ));
  }
}
